#!/bin/bash
#Poorly written by Contro

SELF=$(readlink -f "$0")

#Deciding whether $2 data should be used by script or Png2Dmp
if [ "$2" != "--move" ]
then
  FIRST_WINE_ARG=$2
else
  FIRST_WINE_ARG=$3
fi

#Function for calling Png2Dmp
convert(){
  #Defining and conditioning arguments
  FILE=$(basename "$1")
  FILE_NAME=$(echo $FILE | cut -f 1 -d '.')
  DIR_NAME=$(dirname "$1")
  DMP_DIR="" #Place path to your dump folder inbetween quotes
  
  cd "$DIR_NAME"

  echo "$FILE"
  #Use wine to call Png2Dmp.exe
  WINEDEBUG=-all wine "" "$FILE" $3 $4 $5 #Place path to Png2Dmp.exe inbetween quotes

  if [ "$2" == "--move" ]
  then
    #Moving output files to the dump location
    $(mv "$FILE_NAME.dmp" "$DMP_DIR/$FILE_NAME.dmp")
  fi
}

if [ "$1" == "-r" ];
then
#Run recursively, on all png files from the current directory onwards

  #Safeguard to make sure hundreds or more files get converted
  FILE_COUNT=$(find -name "*.png" -type f | wc -l)
  if [ $FILE_COUNT -ge 100 ];
  then
    echo "ERROR: There are" $FILE_COUNT "files selected for conversion. Ending script"
    exit
  
  else
    find -name "*.png" -exec "$SELF" {} $2 $FIRST_WINE_ARG $4 $5 \;
  fi

else
#Run on one specified file
convert "$1" $2 $FIRST_WINE_ARG $4 $5

fi
